import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dzakki
 */
public class Makanan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Makanan.class.getName());
    
    // Gunakan DefaultListModel untuk menampung pesanan yang sudah dipilih
    private javax.swing.DefaultListModel<String> keranjangPesanan = new javax.swing.DefaultListModel<>();
    /**
     * Creates new form Makanan
     */
    public Makanan() {
        initComponents();
        
        Dropdown.removeAllItems();
        Dropdown.addItem("Makanan");
        Dropdown.addItem("Minuman");

        // Tambahkan baris ini agar user bisa memilih lebih dari satu (tekan Ctrl + Klik)
        ListMenu.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NoMeja = new javax.swing.JTextField();
        PesanField = new javax.swing.JTextField();
        Dropdown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListMenu = new javax.swing.JList<>();
        PesanButton = new javax.swing.JButton();
        TambahButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("APLIKASI PEMESANAN MAKANAN & MINUMAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("No. Meja :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pemesan : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Kategori : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Menu : ");

        Dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        Dropdown.addActionListener(this::DropdownActionPerformed);

        ListMenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListMenu);

        PesanButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PesanButton.setText("Pesan");
        PesanButton.addActionListener(this::PesanButtonActionPerformed);

        TambahButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TambahButton.setText("Tambah");
        TambahButton.addActionListener(this::TambahButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NoMeja)
                                    .addComponent(PesanField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(Dropdown, 0, 162, Short.MAX_VALUE)))
                            .addComponent(PesanButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TambahButton)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NoMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PesanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TambahButton)
                        .addGap(70, 70, 70)))
                .addComponent(PesanButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanButtonActionPerformed
        // TODO add your handling code here:
        if (keranjangPesanan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Keranjang masih kosong!");
        return;
    }

    String nomorMeja = NoMeja.getText();
    String namaPemesan = PesanField.getText();
    StringBuilder daftar = new StringBuilder();
    int totalHarga = 0;

    for (int i = 0; i < keranjangPesanan.getSize(); i++) {
        String item = keranjangPesanan.getElementAt(i);
        daftar.append("- ").append(item).append("\n");
        
        // Ambil harga (setelah tanda -)
        String[] parts = item.split(" - ");
        totalHarga += Integer.parseInt(parts[1].trim());
    }

    String hasil = "Meja: " + nomorMeja + "\nNama: " + namaPemesan + 
                   "\n\nPesanan:\n" + daftar + "\nTotal: Rp " + totalHarga;
    
    JOptionPane.showMessageDialog(this, hasil);
    
    // Opsional: Kosongkan keranjang setelah pesan
    keranjangPesanan.clear();
    }//GEN-LAST:event_PesanButtonActionPerformed

    private void DropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropdownActionPerformed
        // TODO add your handling code here:
        String kategori = Dropdown.getSelectedItem().toString();
    String[] data = null;
    
    if(kategori.equals("Makanan")){
        // Format: Nama Menu - Harga
        data = new String[]{"Nasi Goreng - 15000", "Mie Ayam - 12000", "Bakso - 13000"};
    }
    else if(kategori.equals("Minuman")){
        data = new String[]{"Es Teh - 5000", "Kopi - 7000", "Soda - 10000"};
    }
    ListMenu.setListData(data);
    }//GEN-LAST:event_DropdownActionPerformed

    private void TambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButtonActionPerformed
        // TODO add your handling code here:
        // Ambil item yang dipilih dari ListMenuBerat
    java.util.List<String> selected = ListMenu.getSelectedValuesList();
    for (String item : selected) {
        // Masukkan ke dalam list penampung jika belum ada
        if (!keranjangPesanan.contains(item)) {
            keranjangPesanan.addElement(item);
        }
    }
    JOptionPane.showMessageDialog(this, "Berhasil ditambahkan ke keranjang!");
    }//GEN-LAST:event_TambahButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Makanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Dropdown;
    private javax.swing.JList<String> ListMenu;
    private javax.swing.JTextField NoMeja;
    private javax.swing.JButton PesanButton;
    private javax.swing.JTextField PesanField;
    private javax.swing.JButton TambahButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
